#!/usr/bin/env ruby
require_relative 'twitter_contract'

while true
  ask_credentials

  puts "Enter TwitterSearch query:"
  search_query = gets.chomp


  search(search_query) if search_query.to_s.size > 3
  puts "\n\n"
  puts "Press any key to continue (or `q` to exit)..."
  exit(0) if STDIN.getch.downcase == 'q'
end
